spring:
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5433/car_service
    username: postgres
    password: 1500002006501
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

server:
  port: 7071