spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/car_service
    username: postgres
    password: 1500002006501
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true