create table if not exists cars
(
    id     bigint primary key generated by default as identity,
    brand  varchar(255) not null,
    number varchar(255) not null unique,
    color  varchar(255) not null,
    price  float8       not null
)
