create table if not exists tech_inspection
(
    id       bigint primary key generated by default as identity,
    car_id   bigint       not null
    date_of_inspection date not null,
    address  varchar(255) not null,
    services varchar(255)
    constraint fk_tech_inspection_cars foreign key (car_id) references cars(id) on delete cascade
)