package com.example.carservice.domain.system;

public enum CarBrand {
    TOYOTA, FORD, CHEVROLET, HONDA, NISSAN, VOLKSWAGEN, BMW, MERCEDES,
    AUDI, HYUNDAI, MAZDA, KIA, SUBARU, LEXUS, JEEP, GMC, TESLA, VOLVO,
    PORSCHE, CADILLAC, JAGUAR, CHRYSLER, DODGE, RAM, BUICK, ACURA,
    INFINITI, LINCOLN, MINI, FIAT, MITSUBISHI, SMART, MASERATI, FERRARI,
    LAMBORGHINI, BUGATTI, BENTLEY
}
